### ISSUE TITLE
Conditional PUT, PATCH and DELETE

### ISSUE THREAD

**Issue by tuupola** [micheh/psr7-cache#1]
Hi, thanks for this library, it is a real time saver. Here is an feature request.

I am using psr7-cache in couple of [API projects](https://github.com/tuupola/slim-api-skeleton) to provide caching based on `ETag` and `Last-Modified` headers. I would like to use it also for conditional `PUT`, `PATCH` and `DELETE` methods.  

This can be done by adding support for the two currently missing `If-Match` and `If-Unmodified-Since` headers  which are described in [RFC7232](https://tools.ietf.org/html/rfc7232#section-6).

**Comment by micheh** [comment]
Thank you for the request. I'll look into it in the next couple of days.

**Comment by micheh** [comment]
Implemented with [version 0.5](https://github.com/micheh/psr7-cache/releases/tag/0.5).

Use `$util->hasStateValidator($request)` to check if the request includes an `If-Match` or `If-Unmodified-Since` header and `$util->hasCurrentState($request, $eTag, $lastModified)` to check if the request has the current state.

**Comment by tuupola** [comment]
Excellent. Thanks!
